### ISSUE TITLE
EPIC: IRMA app ombouwen naar YIVI

### ISSUE THREAD

**Issue by marnixdessing** [GemeenteNijmegen/irma-issue-app#39]
## Omschrijving
Ivm de wijziging van de IRMA naam naar YIVI moet de front-end her-ontworpen worden.

## Taken
- [ ] https://github.com/GemeenteNijmegen/irma-issue-app/issues/3
- [ ] https://github.com/GemeenteNijmegen/irma-issue-app/issues/7
- [ ] https://github.com/GemeenteNijmegen/irma-issue-app/issues/8
- [ ] inzicht in aantal bevragingen (zowel uniek als dubbele) zodat we kunnen achterhalen bij welke aangesloten partij het aantal dubbele bevragen plaatsvindt. Dit terugleggen bij SIDN zodat ze met deze partner in gesprek kunnen gaan om dit te beperken.
- [ ] meenemen kosten bevragingen voor management

**Comment by marnixdessing** [comment]
Samengevoegd met https://github.com/GemeenteNijmegen/devops/issues/20
